[project]
name = "giveaway"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "python main.py"

[dependencies]
textual = "0.33.0.*"
